name: Azure Resource Deployment

on:
  workflow_dispatch:
    inputs:
      resource_name:
        description: "name if the resource to deploy"
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Azure deployment
        run: echo "Deploying resource ${{ github.event.inputs.resource_name }}"
