name: eNGine Deployment

on:
  workflow_dispatch:
    inputs:
      azure_region:
        description: ""
        required: true
      azure_subscription:
        description: ""
        required: true
      business_unit:
        description: ""
        required: true
      deploy_aure_ml:
          description: ""
          required: false
          default: "false"
      deploy_azure_open_ai:
          description: ""
          required: false
          default: "false"
      deploy_ai_search:
          description: ""
          required: false
          default: "false"
      deploy_computer_vision:
          description: ""
          required: false
          default: "false"
      deploy_document_intelligence:
          description: ""
          required: false
          default: "false"
      project_name:
        description: ""
        required: true
      user_email:
        description: "The email of the user requesting the deployment"
        required: true
      workflow_id:
        description: "The workflow id"
        required: true
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - id: print_inputs
              name: Print Inputs
              run: |
                echo "Azure Region: ${{ github.event.inputs.azure_region}}"
                echo "Azure Subscription: ${{ github.event.inputs.azure_subscription}}"
                echo "Business Unit: ${{ github.event.inputs.business_unit }}"
                echo "Deploy Azure ML: ${{ github.event.inputs.deploy_aure_ml }}"
                echo "Deploy Azure OpenAI: ${{ github.event.inputs.deploy_azure_open_ai }}"
                echo "Deploy AI Search: ${{ github.event.inputs.deploy_ai_search }}"
                echo "Deploy Computer Vision: ${{ github.event.inputs.deploy_computer_vision }}"
                echo "Deploy Document Intelligence: ${{ github.event.inputs.deploy_document_intelligence }}"
                echo "Project Name:  ${{ github.event.inputs.project_name }}"
                echo "User Email: ${{ github.event.inputs.user_email }}"
                echo "Workflow Id: ${{ github.event.inputs.workflow_id }}"
            - id: create_folder
              name: Create Folder
              run: |
                echo "Creating Folder...."
            - id: copy_template
              name: Copy Template
              run: |
                echo "Copying Template..."
            - id: Write_tfvars
              name: Write TfVars
              run: |
                touch "mytfvars.auto.tfvars"
                echo "azure_region=${{ github.event.inputs.azure_region }}>>mytfvars.auto.tfvars"
