name: Rest API Comm

on:
    [push]

jobs:
    rest_api_parse_json:
        runs-on: ubuntu-latest
        outputs:
            user_email: ${{ steps.parse_json.outputs.user_email}}
        steps:
            - id: parse_json
              name: Rest API Testing
              run: |
                echo "user_email="user.email@email.com"" >> $GITHUB_OUTPUT
    output_results:
        runs-on: ubuntu-latest
        needs: rest_api_parse_json
        steps:
          - env:
              USER_EMAIL: ${{needs.rest_api_parse_json.outputs.user_email}}
            run: |
              echo "$USER_EMAIL"



# /api/v1/workspaces
 
#   "user_email": "new_testuser1@example.com",
#   "resources": [
#     {
#       "region_name": "eastus",
#       "type_name": "Blob Storage",
#       "resource_name": "blob_56258"
#     },
#     {
#       "region_name": "eastus2",
#       "type_name": "ML Workspace",
#       "resource_name": "mlw_56258"
#     }
#   ]
# }