name: eNGine Deployment

on:
  workflow_dispatch:
    inputs:
      
      azure_region:
        description: ""
        required: true
      azure_subscription:
        description: ""
        required: true
      business_unit:
        description: ""
        required: true
      deploy_resources:
        description: ""
        default: "deploy_azure_ml=false,deploy_azure_open_ai=false,deploy_ai_search=false,deploy_computer_vision=false,deploy_document_intelligence=false"
      project_name:
        description: ""
        required: true
      user_email:
        description: "The email of the user requesting the deployment"
        required: true
      workflow_id:
        description: "The workflow id"
        required: true
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - id: print_inputs
              name: Print Inputs
              run: |
                echo "Azure Region: ${{ github.event.inputs.azure_region}}"
                echo "Azure Subscription: ${{ github.event.inputs.azure_subscription}}"
                echo "Business Unit: ${{ github.event.inputs.business_unit }}"
                echo "Deploy Azure ML: ${{ github.event.inputs.deploy_resources }}""
                echo "Project Name:  ${{ github.event.inputs.project_name }}"
                echo "User Email: ${{ github.event.inputs.user_email }}"
                echo "Workflow Id: ${{ github.event.inputs.workflow_id }}"
            - id: create_folder
              name: Create Folder
              run: |
                echo "Creating Folder...."
            - id: copy_template
              name: Copy Template
              run: |
                echo "Copying Template..."
            - id: Write_tfvars
              name: Write TfVars
              run: |
                touch "mytfvars.auto.tfvars"
                echo "azure_region=${{ github.event.inputs.azure_region }}>>mytfvars.auto.tfvars"
