name: Rest API Comm

on:
  workflow_dispatch:
    inputs:
      workflow_id:
        description: "The workflow id"
        required: true
      user_email:
        description: "The email of the user requesting the deployment"
        required: true
      deploy_aure_ml:
          description: ""
          required: false
          default: "false"
      deploy_azure_open_ai:
          description: ""
          required: false
          default: "false"
      deploy_document_intelligence:
          description: ""
          required: false
          default: "false"
      deploy_ai_search:
          description: ""
          required: false
          default: "false"
      deploy_computer_vision:
          description: ""
          required: false
          default: "false"
jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
            - id: parse_json
              name: Rest API Testing
              run: |
                echo "Workflow Id: ${{ github.event.inputs.workflow_id }}"
                echo "User Email: ${{ github.event.inputs.user_email }}"
                echo "Deploy Azure ML: ${{ github.event.inputs.deploy_aure_ml }}"
                echo "Deploy Azure OpenAI: ${{ github.event.inputs.deploy_azure_open_ai }}"
                echo "Deploy Document Intelligence: ${{ github.event.inputs.deploy_document_intelligence }}"
                echo "Deploy AI Search: ${{ github.event.inputs.deploy_ai_search }}"
                echo "Deploy Computer Vision: ${{ github.event.inputs.deploy_computer_vision }}"


# /api/v1/workspaces
 
#   "user_email": "new_testuser1@example.com",
#   "resources": [
#     {
#       "region_name": "eastus",
#       "type_name": "Blob Storage",
#       "resource_name": "blob_56258"
#     },
#     {
#       "region_name": "eastus2",
#       "type_name": "ML Workspace",
#       "resource_name": "mlw_56258"
#     }
#   ]
# }