name: eNGine Deployment

on:
  workflow_dispatch:
    inputs:
      azure_region:
        description: ""
        required: true
        default: "DELETE: EASTUS"
      business_unit:
        description: ""
        required: true
        default: "DELETE: BU"
      deploy_resources:
        description: ""
        default: "deploy_azure_ml=false,deploy_azure_open_ai=false,deploy_ai_search=false,deploy_computer_vision=false,deploy_document_intelligence=false"
      environment:
        description: ""
        required: true
        default: "DELETE: DEV"
      project_name:
        description: ""
        required: true
        default: "DELETE: PRJ"
      user_email:
        description: "The email of the user requesting the deployment"
        required: true
        default: "DELETE: matthew@clark.com"
      workflow_id:
        description: "The workflow id"
        required: true
        default: "DELETE: LKJDLKFJKLSJDFLKJSDLKFJKLSJDF8908098"

env:
  DIRECTORY: "mydir123"
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - id: create_folder
              name: Create Folder
              run: |
                echo "Creating Folder...."
                if [ ! -d "$DIRECTORY" ]; then mkdir "$DIRECTORY"; fi
                ls -al
            - id: copy_template
              name: Copy Template
              run: |
                echo "Copying Template...(overwrite)"
                cp -rf faketftemplate/* $DIRECTORY

                ls -al $DIRECTORY
            - id: Write_tfvars
              name: Write TfVars
              run: |
                cd $DIRECTORY
                touch "mytfvars.auto.tfvars"
                echo "azure_region=${{ github.event.inputs.azure_region }}>>mytfvars.auto.tfvars"

                echo "${{ github.event.inputs.deploy_resources }}" | tr ',' '\n'>>mytfvars.auto.tfvars

                cat mytfvars.auto.tfvars

                
