name: RestAPI Comm

on:
  workflow_dispatch:
    inputs:
      azure_region:
        description: ""
        required: true
        default: "EASTUS"
      business_unit:
        description: ""
        required: true
        default: "DELETE: BU"
      deploy_resources:
        description: ""
        default: "deploy_azure_ml=false,deploy_azure_open_ai=false,deploy_ai_search=false,deploy_computer_vision=false,deploy_document_intelligence=false"
      environment:
        description: ""
        required: true
        default: "DELETE: DEV"
      project_name:
        description: ""
        required: true
        default: "DELETE: PRJ"
      user_email:
        description: "The email of the user requesting the deployment"
        required: true
        default: "matthew@clark.com"
      workflow_id:
        description: "The workflow id"
        required: true
        default: "DELETE: LKJDLKFJKLSJDFLKJSDLKFJKLSJDF8908098"

env:
  DIRECTORY: "./mydir123"
  TEMPLATE: "./faketftemplate"
  TFVARS: "my.auto.tfvars"
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - id: create_folder
              name: Create Folder
              run: |
                echo "Creating Folder...."
                if [ ! -d "$DIRECTORY" ]; then mkdir "$DIRECTORY"; fi
                ls -al
            - id: copy_template
              name: Copy Template
              run: |
                echo "Copying Template...(overwrite)"
                cp -rf $TEMPLATE/* $DIRECTORY
            - id: Write_tfvars
              name: Write TfVars
              run: |
                cd $DIRECTORY
                touch "$TFVARS"
                echo "azure_region = \"${{ github.event.inputs.azure_region }}\"">>$TFVARS
                echo "${{ github.event.inputs.deploy_resources }}" | tr ',' '\n'>>$TFVARS
                echo "ad_user_email = \"${{ github.event.inputs.user_email }}\"">>$TFVARS

                cat $TFVARS